package com.example.ui

object Localization {
    private val translations = mapOf(
        "en" to mapOf(
            "app_title" to "Eye Relief",
            "start_break" to "Start Break",
            "recommended" to "RECOMMENDED BY OPHTHALMOLOGISTS",
            "breaks_today" to "Breaks Today",
            "rest_time" to "Rest Time",
            "ocular_relief" to "Ocular Relief",
            "logs_suffix" to "Logs",
            "target_lang" to "Target Language",
            "target_lang_desc" to "Exercise instructions will be translated seamlessly into this format.",
            "assessed_strain" to "Assessed Screen Strain",
            "assessed_strain_desc" to "How fatigued or heavy do your eyes feel right now?",
            "strain_none" to "None",
            "strain_light" to "Light",
            "strain_medium" to "Medium",
            "strain_severe" to "Severe",
            "wellbeing_log" to "Your Wellbeing Log",
            "clear_history" to "Clear History",
            "no_breaks" to "No breaks saved yet. Breathe and start your first break!",
            "loading_title" to "Consulting Gemini AI Ophthalmic Expert...",
            "loading_desc" to "Drafting a scientifically backed break, optimized to relieve strain in your target language.",
            "relax_eyes" to "Relax Your Eyes",
            "seconds" to "SECONDS",
            "medical_benefit" to "MEDICAL BENEFIT",
            "instructions" to "Instructions",
            "complete_rest" to "Complete Rest",
            "finished_title" to "Screen Break Finished!",
            "finished_desc" to "Assess your current eye comfort levels after finishing the guided exercises.",
            "eyes_feel_prefix" to "My eyes feel",
            "save_log" to "Save to Log Dashboard",
            "cancel_discard" to "Cancel and discard",
            "failed_compile" to "Failed to compile custom exercise",
            "return_dashboard" to "Return to Dashboard",
            "settings_title" to "Settings",
            "settings_lang" to "App Translation",
            "settings_lang_desc" to "Choose the display language for the entire interface.",
            "settings_db" to "Database Management",
            "settings_db_desc" to "Permanently delete your entire break history.",
            "settings_clear_confirm" to "Are you sure you want to clear your history? This action cannot be undone.",
            "cancel" to "Cancel",
            "confirm" to "Confirm",
            "settings_mode" to "Exercise Generation Mode",
            "settings_mode_gemini" to "AI Smart Generation (Gemini)",
            "settings_mode_offline" to "Offline Presets Only (Eco-mode)"
        ),
        "ar" to mapOf(
            "app_title" to "راحة العين",
            "start_break" to "ابدأ الاستراحة",
            "recommended" to "موصى به من قبل أطباء العيون",
            "breaks_today" to "استراحات اليوم",
            "rest_time" to "وقت الراحة",
            "ocular_relief" to "تحسن العين",
            "logs_suffix" to "سجلات",
            "target_lang" to "لغة التمارين",
            "target_lang_desc" to "سيتم توفير تعليمات التمارين بسلاسة بهذه اللغة.",
            "assessed_strain" to "إجهاد العين الحالي",
            "assessed_strain_desc" to "كيف تشعر بالتعب أو الثقل في عينيك الآن؟",
            "strain_none" to "لا يوجد",
            "strain_light" to "خفيف",
            "strain_medium" to "متوسط",
            "strain_severe" to "شديد",
            "wellbeing_log" to "سجل صحة العين",
            "clear_history" to "مسح السجل",
            "no_breaks" to "لا توجد استراحات محفوظة بعد. تنفس وابدأ استراحتك الأولى!",
            "loading_title" to "جاري استشارة خبير طب العيون بالذكاء الاصطناعي...",
            "loading_desc" to "جاري تصميم استراحة علمية مخصصة ومحسنة لتخفيف الإجهاد والتوتر البصري.",
            "relax_eyes" to "أرح عينيك الآن",
            "seconds" to "ثانية",
            "medical_benefit" to "الفائدة الطبية",
            "instructions" to "الخطوات والتعليمات",
            "complete_rest" to "إنهاء مبكر للراحة",
            "finished_title" to "اكتملت الاستراحة بنجاح!",
            "finished_desc" to "يرجى تقييم مستوى راحة عينيك الآن بعد الانتهاء من التمارين.",
            "eyes_feel_prefix" to "أشعر أن عينيَّ",
            "save_log" to "حفظ السجل والعودة",
            "cancel_discard" to "إلغاء وتجاهل السجل",
            "failed_compile" to "فشل إعداد التمرين المخصص",
            "return_dashboard" to "العودة للرئيسية",
            "settings_title" to "الضبط",
            "settings_lang" to "لغة واجهة التطبيق",
            "settings_lang_desc" to "اختر لغة عرض الواجهات وتعديل التعليمات الإرشادية.",
            "settings_db" to "إدارة قاعدة البيانات",
            "settings_db_desc" to "حذف جميع سجلات الاستراحات السابقة نهائيًا.",
            "settings_clear_confirm" to "هل أنت متأكد من رغبتك في مسح السجل؟ لا يمكن التراجع عن هذا الإجراء.",
            "cancel" to "إلغاء",
            "confirm" to "تأكيد",
            "settings_mode" to "طريقة جلب التمارين",
            "settings_mode_gemini" to "ذكاء اصطناعي ذكي (Gemini)",
            "settings_mode_offline" to "التمارين المخزنة مسبقًا فقط (توفير البيانات)"
        ),
        "fr" to mapOf(
            "app_title" to "Soulagement des Yeux",
            "start_break" to "Démarrer la pause",
            "recommended" to "RECOMMANDÉ PAR LES OPHTALMOLOGISTES",
            "breaks_today" to "Pauses aujourd'hui",
            "rest_time" to "Temps de repos",
            "ocular_relief" to "Soulagement oculaire",
            "logs_suffix" to "Journaux",
            "target_lang" to "Langue cible",
            "target_lang_desc" to "Les instructions de l'exercice seront traduites de manière transparente.",
            "assessed_strain" to "Fatigue oculaire estimée",
            "assessed_strain_desc" to "À quel point vos yeux sont-ils fatigués ou lourds en ce moment ?",
            "strain_none" to "Aucune",
            "strain_light" to "Léger",
            "strain_medium" to "Moyen",
            "strain_severe" to "Sévère",
            "wellbeing_log" to "Votre journal de bien-être",
            "clear_history" to "Effacer l'historique",
            "no_breaks" to "Aucune pause enregistrée. Respirez et commencez votre première pause !",
            "loading_title" to "Consultation de l'expert en ophtalmologie Gemini AI...",
            "loading_desc" to "Rédaction d'une pause scientifiquement prouvée, optimisée pour soulager la fatigue.",
            "relax_eyes" to "Détendez vos yeux",
            "seconds" to "SECONDES",
            "medical_benefit" to "BÉNÉFICE MÉDICAL",
            "instructions" to "Instructions",
            "complete_rest" to "Pause complète",
            "finished_title" to "Pause d'écran terminée !",
            "finished_desc" to "Évaluez votre niveau de confort oculaire actuel après avoir terminé les exercices.",
            "eyes_feel_prefix" to "Mes yeux se sentent",
            "save_log" to "Enregistrer et revenir",
            "cancel_discard" to "Annuler et ignorer",
            "failed_compile" to "Échec de la compilation de l'exercice",
            "return_dashboard" to "Retour au tableau",
            "settings_title" to "Paramètres",
            "settings_lang" to "Langue de l'application",
            "settings_lang_desc" to "Choisissez la langue d'affichage de l'interface entière.",
            "settings_db" to "Gestion de la base de données",
            "settings_db_desc" to "Supprimer définitivement tout votre historique de pauses.",
            "settings_clear_confirm" to "Voulez-vous vraiment effacer votre historique ? Cette action est irréversible.",
            "cancel" to "Annuler",
            "confirm" to "Confirmer",
            "settings_mode" to "Génération d'exercices",
            "settings_mode_gemini" to "Génération intelligente IA (Gemini)",
            "settings_mode_offline" to "Préréglages hors ligne uniquement"
        ),
        "de" to mapOf(
            "app_title" to "Augenentlastung",
            "start_break" to "Pause starten",
            "recommended" to "VON AUGENÄRZTEN EMPFOHLEN",
            "breaks_today" to "Pausen heute",
            "rest_time" to "Ruhezeit",
            "ocular_relief" to "Okulare Entlastung",
            "logs_suffix" to "Protokolle",
            "target_lang" to "Zielsprache",
            "target_lang_desc" to "Die Übungsanweisungen werden nahtlos in dieses Format übersetzt.",
            "assessed_strain" to "Eingeschätzte Augenbelastung",
            "assessed_strain_desc" to "Wie müde oder schwer fühlen sich Ihre Augen gerade an?",
            "strain_none" to "Keine",
            "strain_light" to "Leicht",
            "strain_medium" to "Mittel",
            "strain_severe" to "Schwer",
            "wellbeing_log" to "Ihr Wohlbefinden-Protokoll",
            "clear_history" to "Verlauf löschen",
            "no_breaks" to "Noch keine Pausen gespeichert. Atmen Sie durch und starten Sie Ihre erste Pause!",
            "loading_title" to "Konsultiere den Gemini-KI-Augenarzt-Experten...",
            "loading_desc" to "Erstellung einer wissenschaftlich fundierten Pause, optimiert zur Linderung der Belastung.",
            "relax_eyes" to "Entspannen Sie Ihre Augen",
            "seconds" to "SEKUNDEN",
            "medical_benefit" to "MEDIZINISCHER NUTZEN",
            "instructions" to "Anweisungen",
            "complete_rest" to "Pause beenden",
            "finished_title" to "Bildschirmpause beendet!",
            "finished_desc" to "Beurteilen Sie Ihren aktuellen Augenkomfort nach Abschluss der Übungen.",
            "eyes_feel_prefix" to "Meine Augen fühlen sich",
            "save_log" to "Im Protokoll speichern",
            "cancel_discard" to "Abbrechen und verwerfen",
            "failed_compile" to "Fehler beim Erstellen der Übung",
            "return_dashboard" to "Zurück zum Dashboard",
            "settings_title" to "Einstellungen",
            "settings_lang" to "Zielsprache der App",
            "settings_lang_desc" to "Wählen Sie die Anzeigesprache für die gesamte Benunzerfläche.",
            "settings_db" to "Datenbankverwaltung",
            "settings_db_desc" to "Löschen Sie Ihren gesamten Pausenverlauf dauerhaft.",
            "settings_clear_confirm" to "Möchten Sie Ihren Verlauf wirklich löschen? Dies kann nicht rückgängig gemacht werden.",
            "cancel" to "Abbrechen",
            "confirm" to "Bestätigen",
            "settings_mode" to "Übungsgenerierungsmodus",
            "settings_mode_gemini" to "KI-Generierung (Gemini)",
            "settings_mode_offline" to "Nur Offline-Voreinstellungen"
        ),
        "es" to mapOf(
            "app_title" to "Alivio Ocular",
            "start_break" to "Iniciar descanso",
            "recommended" to "RECOMENDADO POR OFTALMÓLOGOS",
            "breaks_today" to "Descansos hoy",
            "rest_time" to "Tiempo de descanso",
            "ocular_relief" to "Alivio ocular",
            "logs_suffix" to "Registros",
            "target_lang" to "Idioma objetivo",
            "target_lang_desc" to "Las instrucciones del ejercicio se traducirán sin problemas.",
            "assessed_strain" to "Fatiga visual estimada",
            "assessed_strain_desc" to "¿Qué tan fatigados o pesados siente sus ojos en este momento?",
            "strain_none" to "Ninguna",
            "strain_light" to "Leve",
            "strain_medium" to "Moderado",
            "strain_severe" to "Severo",
            "wellbeing_log" to "Su registro de bienestar",
            "clear_history" to "Limpiar historial",
            "no_breaks" to "Aún no hay descansos guardados. ¡Respire y comience su primer descanso!",
            "loading_title" to "Consultando al experto oftálmico de Gemini AI...",
            "loading_desc" to "Diseñando un descanso con base científica, optimizado para aliviar la fatiga.",
            "relax_eyes" to "Relaje sus ojos",
            "seconds" to "SEGUNDOS",
            "medical_benefit" to "BENEFICIO MÉDICO",
            "instructions" to "Instrucciones",
            "complete_rest" to "Terminar",
            "finished_title" to "¡Descanso de pantalla completado!",
            "finished_desc" to "Evalúe su nivel de comodidad visual actual después de terminar el ejercicio.",
            "eyes_feel_prefix" to "Mis ojos se sienten",
            "save_log" to "Guardar en el registro",
            "cancel_discard" to "Cancelar y descartar",
            "failed_compile" to "Error al compilar el ejercicio",
            "return_dashboard" to "Volver al tablero",
            "settings_title" to "Ajustes",
            "settings_lang" to "Idioma de la aplicación",
            "settings_lang_desc" to "Elija el idioma de visualización de toda la interfaz.",
            "settings_db" to "Gestión de bases de datos",
            "settings_db_desc" to "Elimine permanentemente todo su historial de descansos.",
            "settings_clear_confirm" to "¿Está seguro de que desea limpiar su historial? Esta acción no se puede deshacer.",
            "cancel" to "Cancelar",
            "confirm" to "Confirmar",
            "settings_mode" to "Modo de generación de ejercicios",
            "settings_mode_gemini" to "Generación inteligente IA (Gemini)",
            "settings_mode_offline" to "Solo preajustes sin conexión"
        )
    )

    fun get(langCode: String, key: String): String {
        val normalizedCode = langCode.trim().lowercase()
        val dict = translations[normalizedCode] ?: translations["en"]!!
        return dict[key] ?: dict["en"] ?: key
    }
}
